"""add anxiety_presentations to patient_profiles

Revision ID: 115688ae4edd
Revises: a104e578fb08
Create Date: 2026-06-02 12:19:53.042433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115688ae4edd'
down_revision: Union[str, None] = 'a104e578fb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('anxiety_presentations', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'anxiety_presentations')
    # ### end Alembic commands ###
