"""add parent_phone to monitoring_forms and reminder_sent_at to experiments

Revision ID: 24389a25f055
Revises: bdfa926fbfec
Create Date: 2026-04-11 17:41:49.731316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24389a25f055'
down_revision: Union[str, None] = 'bdfa926fbfec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitoring_forms', sa.Column('parent_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_forms', 'parent_phone')
    op.drop_column('experiments', 'reminder_sent_at')
    # ### end Alembic commands ###
