"""add committed_at and too_hard_at to experiments

Revision ID: 47c3125ea917
Revises: 8463c3edba59
Create Date: 2026-04-07 10:39:55.886630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c3125ea917'
down_revision: Union[str, None] = '8463c3edba59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('experiments', sa.Column('too_hard_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'too_hard_at')
    op.drop_column('experiments', 'committed_at')
    # ### end Alembic commands ###
