"""add accommodator field to accommodation_behaviors

Revision ID: 8463c3edba59
Revises: 917202c93f21
Create Date: 2026-04-06 10:42:45.178725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8463c3edba59'
down_revision: Union[str, None] = '917202c93f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation_behaviors', sa.Column('accommodator', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodation_behaviors', 'accommodator')
    # ### end Alembic commands ###
