"""add clinical_formulations table

Revision ID: 8af0210c34e6
Revises: 115688ae4edd
Create Date: 2026-06-02 12:20:34.250588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af0210c34e6'
down_revision: Union[str, None] = '115688ae4edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_formulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('practitioner_id', sa.Uuid(), nullable=False),
    sa.Column('maintaining_mechanisms', sa.Text(), nullable=True),
    sa.Column('accommodation_patterns', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('treatment_targets', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioner_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_formulations')
    # ### end Alembic commands ###
