"""replace date_of_birth with age and gender

Revision ID: 916666bb0584
Revises: a53a20f5eacd
Create Date: 2026-04-13 19:41:50.624679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916666bb0584'
down_revision: Union[str, None] = 'a53a20f5eacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('patient_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.drop_column('patient_profiles', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('patient_profiles', 'gender')
    op.drop_column('patient_profiles', 'age')
    # ### end Alembic commands ###
