"""add_is_active_to_trigger_situations

Revision ID: a53a20f5eacd
Revises: 24389a25f055
Create Date: 2026-04-11 22:02:49.247782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53a20f5eacd'
down_revision: Union[str, None] = '24389a25f055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trigger_situations', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trigger_situations', 'is_active')
    # ### end Alembic commands ###
