"""add phone_number to patient_profiles and parent_patient_links

Revision ID: bdfa926fbfec
Revises: ccd2de175cb0
Create Date: 2026-04-10 09:11:53.104007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfa926fbfec'
down_revision: Union[str, None] = 'ccd2de175cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_patient_links', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'phone_number')
    op.drop_column('parent_patient_links', 'phone_number')
    # ### end Alembic commands ###
