"""add content field to action_plans

Revision ID: ccd2de175cb0
Revises: 4cb138c697ee
Create Date: 2026-04-08 10:56:03.650612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccd2de175cb0'
down_revision: Union[str, None] = '4cb138c697ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_plans', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_plans', 'content')
    # ### end Alembic commands ###
