"""add nickname to treatment_plans

Revision ID: e2ead5cd800f
Revises: 916666bb0584
Create Date: 2026-04-14 19:33:14.663354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ead5cd800f'
down_revision: Union[str, None] = '916666bb0584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_plans', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_plans', 'nickname')
    # ### end Alembic commands ###
