"""add activated_at to treatment_plans

Revision ID: fe555be26e27
Revises: 576e314c49f0
Create Date: 2026-04-15 09:46:57.160056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe555be26e27'
down_revision: Union[str, None] = '576e314c49f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treatment_plans', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treatment_plans', 'activated_at')
    # ### end Alembic commands ###
